[package]
name = "containerd-shim-runc-v2"
version = "0.1.0"
authors = ["Shaobao Feng <fshb1988@gmail.com>", "Tianyang Zhang <burning9699@gmail.com>", "The containerd Authors"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/containerd/rust-extensions"
keywords = ["containerd", "shim", "containers"]
description = "Rust implementation of containerd's runc v2 shim runtime"
homepage = "https://containerd.io"

[features]
async = []

[dependencies]
log = "0.4"
nix = "0.23.1"
libc = "0.2.95"
time = { version = "0.3.7", features = ["serde", "std"] }
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
oci-spec = "0.5.4"
crossbeam = "0.8.1"

containerd-shim = { path = "../shim", version = "0.2.0" }
runc = { path = "../runc", version = "0.1.0" }

[target.'cfg(target_os = "linux")'.dependencies]
cgroups-rs = "0.2.8"
