[package]
name = "containerd-shim-runc-v2"
version = "0.1.0"
authors = ["Shaobao Feng <fshb1988@gmail.com>", "Tianyang Zhang <burning9699@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
async = []

[dependencies]
containerd-shim = { path = "../shim", version = "0.2.0" }
nix = "0.23.1"
time = { version = "0.3.7", features = ["serde", "std"] }
log = { version = "0.4.11", features = ["std"] }
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
oci-spec = "0.5.4"

runc = { path = "../runc", version = "0.1.0" }

[profile.release]
panic = 'abort'
